trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  paths:
    exclude:
    - docs/*
    - .github/*
    - LICENSE
    - README.md
    - .appveyor.yml
    - .travis.yml
pr:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  paths:
    exclude:
    - docs/*
    - .github/*
    - LICENSE
    - README.md
    - .appveyor.yml
    - .travis.yml

jobs:
- job:
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Release:
        configuration: Release
  steps:
  - script: |
      git config --global core.autocrlf input
      xb setup
    displayName: 'Setup'

  - script: xb build --config=$(configuration) --target=src\xenia-app --target=src\xenia-vfs-dump
    displayName: 'Build $(configuration)'

  - script: |
      cd build\bin\Windows\$(configuration)
      7z a $(Build.ArtifactStagingDirectory)\xenia-$(Build.SourceBranchName).zip ..\..\..\..\LICENSE ..\..\..\..\README.md xenia.exe xenia.pdb
      7z a $(Build.ArtifactStagingDirectory)\xenia-vfs-dump-$(Build.SourceBranchName).zip ..\..\..\..\LICENSE xenia-vfs-dump.exe xenia-vfs-dump.pdb
    displayName: 'Create archives'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: $(configuration)
    displayName: Publish artifacts
